# Generated by Django 4.2.11 on 2025-11-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mensalidade')),
                ('due_day', models.PositiveSmallIntegerField(default=5, verbose_name='Dia de vencimento')),
                ('payment_link', models.URLField(blank=True, verbose_name='Link de pagamento')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('delinquent', 'Inadimplente'), ('settled', 'Quitado')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('name',),
            },
        ),
    ]
