# Generated by Django 4.2.11 on 2025-11-11 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='due_date',
            field=models.DateField(default=datetime.date.today, help_text='Próxima data de cobrança.', verbose_name='Data de vencimento'),
        ),
    ]
