# Generated by Django 4.2.11 on 2025-11-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auto_messaging_enabled',
            field=models.BooleanField(default=True, help_text='Quando ativo, o sistema enviará mensagens automáticas nas datas configuradas.', verbose_name='Envio automático habilitado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='due_day',
            field=models.PositiveSmallIntegerField(default=5, editable=False, verbose_name='Dia de vencimento'),
        ),
    ]
