# Generated by Django 4.2.11 on 2025-11-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_auto_messaging_enabled_alter_client_due_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='vehicle_type',
            field=models.CharField(choices=[('moto', 'Moto'), ('carro', 'Carro')], default='moto', help_text='Tipo de veículo do cliente (Moto = R$ 49,99, Carro = R$ 59,99)', max_length=10, verbose_name='Tipo de Veículo'),
        ),
    ]
