# Generated by Django 4.2.11 on 2025-11-11 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], default='whatsapp', max_length=20, verbose_name='Canal')),
                ('body', models.TextField(verbose_name='Corpo da mensagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de mensagem',
                'verbose_name_plural': 'Templates de mensagem',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('reminder', 'Lembrete'), ('charge', 'Cobrança')], max_length=20, verbose_name='Tipo de mensagem')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], max_length=20, verbose_name='Canal')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('failed', 'Falha')], max_length=20, verbose_name='Status do envio')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Data envio')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Payload enviado')),
                ('response', models.JSONField(blank=True, null=True, verbose_name='Resposta do provedor')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='messaging.messagetemplate')),
            ],
            options={
                'verbose_name': 'Log de envio',
                'verbose_name_plural': 'Logs de envio',
                'ordering': ('-sent_at',),
            },
        ),
        migrations.CreateModel(
            name='ClientInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Data recebimento')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], default='whatsapp', max_length=20, verbose_name='Canal')),
                ('raw_message', models.TextField(verbose_name='Mensagem recebida')),
                ('normalized_option', models.CharField(blank=True, max_length=50, verbose_name='Opção normalizada')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='clients.client')),
                ('message_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='messaging.messagelog')),
            ],
            options={
                'verbose_name': 'Interação do cliente',
                'verbose_name_plural': 'Interações dos clientes',
                'ordering': ('-received_at',),
            },
        ),
    ]
