# Generated by Django 4.2.11 on 2025-11-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_default_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='message_type',
            field=models.CharField(choices=[('reminder', 'Lembrete'), ('charge', 'Cobrança'), ('incoming', 'Recebida')], max_length=20, verbose_name='Tipo de mensagem'),
        ),
    ]
