"""
Django settings for cobranca_chatbot project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from celery.schedules import crontab
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "unsafe-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"

# Configurar ALLOWED_HOSTS
if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    # Em produção, ler de variável de ambiente
    allowed_hosts_env = os.getenv("DJANGO_ALLOWED_HOSTS", "")
    if allowed_hosts_env:
        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split() if host.strip()]
    else:
        # Se não configurado e estiver no Render, aceitar qualquer domínio .onrender.com
        # O Render define RENDER_EXTERNAL_HOSTNAME automaticamente
        render_host = os.getenv("RENDER_EXTERNAL_HOSTNAME", "")
        if render_host:
            ALLOWED_HOSTS = [render_host]
        else:
            # Verificar se está no Koyeb (detecta domínio .koyeb.app)
            koyeb_host = os.getenv("KOYEB_APP_URL", "").replace("https://", "").replace("http://", "")
            if koyeb_host and ".koyeb.app" in koyeb_host:
                ALLOWED_HOSTS = [koyeb_host, "localhost", "127.0.0.1"]
            else:
                # Adicionar domínio do Koyeb hardcoded (fallback)
                ALLOWED_HOSTS = ["acute-crab-thiagocobrancas-328dda69.koyeb.app", "localhost", "127.0.0.1"]

# CSRF Trusted Origins (necessário para Fly.io)
CSRF_TRUSTED_ORIGINS = []

# Primeiro, verificar se está definido via variável de ambiente
csrf_env = os.getenv("CSRF_TRUSTED_ORIGINS", "")
if csrf_env:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_env.split() if origin.strip()]

# Se não definido e em produção, usar ALLOWED_HOSTS
if not CSRF_TRUSTED_ORIGINS and not DEBUG and ALLOWED_HOSTS:
    CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS if host and host != "*"]

# Em desenvolvimento, permitir localhost
if not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = ["http://localhost:8000", "http://127.0.0.1:8000"]

# Garantir que o domínio do Koyeb está sempre incluído (se detectado)
koyeb_url = os.getenv("KOYEB_APP_URL", "")
if koyeb_url and ".koyeb.app" in koyeb_url:
    if not koyeb_url.startswith("https://"):
        koyeb_url = f"https://{koyeb_url}"
    if koyeb_url not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(koyeb_url)

# Adicionar domínio do Koyeb hardcoded (fallback se variável não estiver configurada)
koyeb_domain = "https://acute-crab-thiagocobrancas-328dda69.koyeb.app"
if koyeb_domain not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(koyeb_domain)

# Garantir que o domínio do Fly.io está sempre incluído (fallback)
fly_domain = "https://chatbot-cobrana-silent-feather-3785.fly.dev"
if fly_domain not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(fly_domain)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_celery_beat',
    'clients.apps.ClientsConfig',  # Usar ClientsConfig para carregar signals
    'messaging',
    'automation',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cobranca_chatbot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cobranca_chatbot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Usar SQLite por padrão (gratuito)
# Se DATABASE_URL estiver definido (PostgreSQL), usar ele; senão usar SQLite
DATABASE_URL = os.getenv('DATABASE_URL', '')

if DATABASE_URL:
    # Usar PostgreSQL se DATABASE_URL estiver definido
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Usar SQLite (gratuito)
    # No Fly.io, usar volume persistente se disponível, senão usar diretório padrão
    db_path = os.getenv('DATABASE_PATH', str(BASE_DIR / 'db.sqlite3'))
    # Se estiver no Fly.io e houver volume montado em /data, usar ele
    # Criar diretório /data se não existir (para quando volume for montado)
    data_dir = Path('/data')
    if data_dir.exists() and data_dir.is_dir():
        db_path = '/data/db.sqlite3'
        # Garantir que o diretório existe e tem permissões
        try:
            data_dir.mkdir(parents=True, exist_ok=True)
        except:
            pass
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': db_path,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Session and CSRF cookie settings for HTTPS (Fly.io)
SESSION_COOKIE_SECURE = not DEBUG  # True em produção (HTTPS)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG  # True em produção (HTTPS)
CSRF_COOKIE_HTTPONLY = False  # False para permitir JavaScript ler o cookie (necessário para AJAX)
CSRF_COOKIE_SAMESITE = 'Lax'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Celery configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

CELERY_BEAT_SCHEDULE = {
    'send_reminders_daily': {
        'task': 'automation.tasks.send_reminder_messages',
        'schedule': crontab(minute=0, hour=9),
    },
    'send_charges_daily': {
        'task': 'automation.tasks.send_charge_messages',
        'schedule': crontab(minute=0, hour=9),
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}


# WhatsApp provider configuration
WHATSAPP_PROVIDER = os.getenv('WHATSAPP_PROVIDER', 'meta').lower()
WHATSAPP_API_URL = os.getenv('WHATSAPP_API_URL', 'https://graph.facebook.com/v18.0')
WHATSAPP_ACCESS_TOKEN = os.getenv('WHATSAPP_ACCESS_TOKEN', '')
WHATSAPP_PHONE_NUMBER_ID = os.getenv('WHATSAPP_PHONE_NUMBER_ID', '')

# WHAPI (whapi.cloud) specific settings
WHAPI_BASE_URL = os.getenv('WHAPI_BASE_URL', 'https://gate.whapi.cloud')
WHAPI_CHANNEL_TYPE = os.getenv('WHAPI_CHANNEL_TYPE', 'web')
WHAPI_TOKEN = os.getenv('WHAPI_TOKEN', '')

# Infobip WhatsApp settings
INFOBIP_BASE_URL = os.getenv('INFOBIP_BASE_URL', '')
INFOBIP_API_KEY = os.getenv('INFOBIP_API_KEY', '')
INFOBIP_SENDER = os.getenv('INFOBIP_SENDER', '')

# WPPConnect Bot settings
WPPCONNECT_BOT_URL = os.getenv('WPPCONNECT_BOT_URL', 'http://localhost:3001')
